version: '2'
services:
  surrogates:
    build:
      context: ./surrogates
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    command: /bin/bash -c "while :; do echo 'Hit CTRL+C'; sleep 1; done"
    volumes:
        - ../target/:/var/app/current
        
