version: '2'
services:
  surrogates:
    build:
      context: ./surrogates
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    command: 
      - /bin/bash
      - -c 
      - |
        cd /var/app/current
        mvn clean compile package
        export R_HOME="/usr/lib64/R"
        java -jar target/uk.ac.kcl.mdeoptimise.service-composition.surrogates-0.0.1-SNAPSHOT-jar-with-dependencies.jar
    volumes:
        - ../:/var/app/current
        
